README.md
=> Add a test commit

frontend/src/views/orders/read/index.js
Ajuste na visualizacao do preco do produto no pedido
=> Ajuste preco

frontend/src/store/ducks/bank.js, frontend/src/store/ducks/bankAccount.js, frontend/src/store/ducks/index.js, frontend/src/store/sagas/index.js, frontend/src/views/events/trainings/create/index.js, frontend/src/views/profile/tabs.js
criacao de treinamento com adicao de contas bancarias
=> feat: create training

frontend/src/store/sagas/index.js, frontend/src/views/orders/create/index.js
boleto de treinamento e seminarios tem prazo de 60 dias
=> fix: formas de pagamento

frontend/src/views/events/groups/edit/churchsTable.js, frontend/src/views/events/groups/edit/index.js
pode alterar a igreja na tela de edicao do evento
=> feat: editar igreja

frontend/src/views/admin/consult/events/table.js, frontend/src/views/events/groups/edit/index.js
teste no download csv e apaguei uns codigos comentados
=> fix: download csv

frontend/src/views/admin/consult/entities/table.js, frontend/src/views/events/groups/edit/index.js
mensagem de finalizar inscricoes explicando novo processo
=> feat: finalizar inscricoes

frontend/src/views/admin/consult/entities/tablePJ.js
=> fix: download csv organizations

frontend/src/views/events/groups/edit/index.js, frontend/src/views/tag/index.js
Ao finalizar o curso, abre-se um modal para confirmar o endereco para o envio do certificado. E na hora da impressao de etiquetas, os enderecos foram corrigidos para o endereco que o lider confirmou na hora de finalizar o evento, pelo campo main_address
=> feat: endereco certificado

frontend/src/store/ducks/participant.js, frontend/src/store/sagas/index.js, frontend/src/views/events/groups/edit/index.js
os lideres agora podem receber os certificados impressos e com o print_date, igual os participantes
=> feat: printed certificates

frontend/src/store/sagas/index.js, frontend/src/views/events/groups/edit/index.js, frontend/src/views/orders/create/index.js
pagamento em boleto de treinamento e seminario alterados de 60 para 30 dias
=> fix: formas de pagamento boleto treinamento e seminario

frontend/package.json, frontend/src/app/router.js, frontend/src/assets/scss/core/_helper.scss, frontend/src/store/ducks/invite.js, frontend/src/store/ducks/participant.js, frontend/src/store/sagas/index.js, frontend/src/views/events/groups/edit/index.js, frontend/src/views/pages/inviteConfirmationBuyer/index.js, frontend/src/views/pages/inviteConfirmationBuyer/utils.js
criacao de uma nova opcao para cadastro de participante com opcao de compra
=> feat: new option add participant

frontend/package.json, frontend/src/store/ducks/participant.js, frontend/src/store/sagas/index.js, frontend/src/views/pages/inviteConfirmationBuyer/index.js
ajustes na criacao do pedido logo apos o commit
=> fix: criacao pedido apos o convite

frontend/src/store/sagas/index.js, frontend/src/views/events/groups/edit/participantTable.js, frontend/src/views/pages/inviteConfirmationBuyer/index.js
ajuste na data de expiracao boleto e validacao email valido no convite
=> fix: boleto invite

frontend/src/store/sagas/index.js, frontend/src/views/events/groups/edit/index.js
ajuste no bloqueio do botao de adicionar participantes, verificando os convites tambem
=> fix: event add participants

frontend/src/store/ducks/participant.js, frontend/src/store/sagas/index.js, frontend/src/views/events/groups/edit/index.js
nova opcao para quando finalizar inscricao receber o certificado impresso ou digital
=> fix: new option finish inscription

frontend/src/views/admin/consult/entities/edit/tabs.js
grupo aonde o participante é desistente nao aparece no historico
=> fix: tabela de historico participante

frontend/src/views/events/groups/edit/index.js
=> fix: ajuste certificado digital

frontend/src/views/events/groups/index.js, frontend/src/views/orders/create/index.js, frontend/src/views/pages/inviteConfirmationBuyer/index.js, frontend/src/views/pages/inviteTrainingConfirmationBuyer/index.js
=> fix changes end year

frontend/src/store/sagas/index.js, frontend/src/views/orders/create/index.js
Ajuste prazo de boleto e frete gratis
=> fix boleto

frontend/src/assets/data/faq.js, frontend/src/views/events/trainings/edit/index.js, frontend/src/views/orders/create/index.js
ajuste textos faq, edicao de treinamento
=> feature training

frontend/src/store/ducks/participant.js, frontend/src/store/sagas/index.js, frontend/src/views/events/groups/edit/lesson/index.js, frontend/src/views/events/trainings/edit/index.js, frontend/src/views/events/trainings/edit/participantTable.js, frontend/src/views/events/trainings/index.js
table participants e aba de finalizacao
=> fix training feature

frontend/src/views/events/trainings/create/index.js, frontend/src/views/pages/inviteTrainingConfirmationBuyer/index.js
=> ajuste convite

frontend/src/views/admin/consult/events/table.js, frontend/src/views/pages/site/components/Body.js
=> Atualizar develop

frontend/src/views/events/trainings/edit/index.js
adjust additional_information and contact
=> fix: edit-training
